<?php

$data = [
    [
        'caste'          => 'Agarwal',
        'gotra'          => 'Airan/Aeron',
        'original_gotra' => 'Aurva',
        'lord'           => 'Indramal',
        'saint'          => 'Atri/Aaurva',
        'veda'           => 'Atri/Aaurva',
        'branch'         => 'Madhyadini/Madhuri',
        'sutra'          => 'Kaatyayni',
    ],
    [
        'caste'          => 'Agarwal',
        'gotra'          => 'Bansal',
        'original_gotra' => 'Vatsya',
        'lord'           => 'Virbhan',
        'saint'          => 'Vishist/Vatsa',
        'veda'           => 'Samaveda',
        'branch'         => 'Kouthmi/Kauttham',
        'sutra'          => 'Gobhil',
    ],
    [
        'caste'          => 'Agarwal',
        'gotra'          => 'Bindal or Vindal',
        'original_gotra' => 'Vishist',
        'lord'           => 'Vrinddev',
        'saint'          => 'Yavasya or Vashista',
        'veda'           => 'Yajurveda',
        'branch'         => 'Madhuri',
        'sutra'          => 'Kaatyayni',
    ],
    [
        'caste'          => 'Agarwal',
        'gotra'          => 'Bhandal',
        'original_gotra' => 'Dhoumya',
        'lord'           => 'Vasudev',
        'saint'          => 'Bhardwaj',
        'veda'           => 'Yajurveda',
        'branch'         => 'Madhyadini or Madhuri',
        'sutra'          => 'Kaatyayni',
    ],
    [
        'caste'          => 'Agarwal',
        'gotra'          => 'Dharan or Deran',
        'original_gotra' => 'Dhanyas',
        'lord'           => 'Dhavandev',
        'saint'          => 'Bhekaar or Ghaumya',
        'veda'           => 'Yajurveda',
        'branch'         => 'Madhuri',
        'sutra'          => 'Kaatyayni',
    ],
    [
        'caste'          => 'Agarwal',
        'gotra'          => 'Garg or Gargeya',
        'original_gotra' => 'Gargasya',
        'lord'           => 'Pushpadev',
        'saint'          => 'Gargacharya or Garg',
        'veda'           => 'Yajurveda',
        'branch'         => 'Madhuri',
        'sutra'          => 'Kaatyayni',
    ],
    [
        'caste'          => 'Agarwal',
        'gotra'          => 'Goyal, Goel or Goenka',
        'original_gotra' => 'Gomil',
        'lord'           => 'Gendumal',
        'saint'          => 'Gautam or Gobhil',
        'veda'           => 'Yajurveda',
        'branch'         => 'Madhuri',
        'sutra'          => 'Kaatyayni',
    ],
    [
        'caste'          => 'Agarwal',
        'gotra'          => 'Goyan, Gangal',
        'original_gotra' => 'Gautan',
        'lord'           => 'Godhar',
        'saint'          => 'Purohit or Gautam',
        'veda'           => 'Yajurveda',
        'branch'         => 'Madhyadini or Madhuri',
        'sutra'          => 'Kaatyayni',
    ],
    [
        'caste'          => 'Agarwal',
        'gotra'          => 'Jindal',
        'original_gotra' => 'Gemino',
        'lord'           => 'Jaitrasangh',
        'saint'          => 'Bruhaspati or Jaimini',
        'veda'           => 'Yajurveda',
        'branch'         => 'Madhyadini or Madhuri',
        'sutra'          => 'Kaatyayni',
    ],
    [
        'caste'          => 'Agarwal',
        'gotra'          => 'Kansal',
        'original_gotra' => 'Kaushik',
        'lord'           => 'Manipal',
        'saint'          => 'Kaushik',
        'veda'           => 'Yajurveda',
        'branch'         => 'Madhyadini or Madhuri',
        'sutra'          => 'Kaatyayni',
    ],
    [
        'caste'          => 'Agarwal',
        'gotra'          => 'Kuchhal, Kuchchal',
        'original_gotra' => 'Kashyap',
        'lord'           => 'Karanchand',
        'saint'          => 'Kush or Kashyap',
        'veda'           => 'Samaveda',
        'branch'         => 'Kosami or Kauttham',
        'sutra'          => 'Komaal',
    ],
    [
        'caste'          => 'Agarwal',
        'gotra'          => 'Madhukul/Mudgal',
        'original_gotra' => 'Mudgal',
        'lord'           => 'Madhavsen',
        'saint'          => 'Aashvalayan/Mudgal',
        'veda'           => 'Rigveda/Yajurveda',
        'branch'         => 'Saalaya/Sakalya',
        'sutra'          => 'Aslayin',
    ],
    [
        'caste'          => 'Agarwal',
        'gotra'          => 'Mangal',
        'original_gotra' => 'Maandav',
        'lord'           => 'Amritsen',
        'saint'          => 'Mudragal/Mandavya',
        'veda'           => 'Rigveda/Yajurveda',
        'branch'         => 'Sakalya',
        'sutra'          => 'Asusai',
    ],
    [
        'caste'          => 'Agarwal',
        'gotra'          => 'Mittal',
        'original_gotra' => 'Maitreya',
        'lord'           => 'Mantrapati',
        'saint'          => 'Vishwamitra/Maitreya',
        'veda'           => 'Yajurveda',
        'branch'         => 'Madhyadini/Madhuri',
        'sutra'          => 'Kaatyayni',
    ],
    [
        'caste'          => 'Agarwal',
        'gotra'          => 'Nangal/Nagal',
        'original_gotra' => 'Naagend',
        'lord'           => 'Narsev',
        'saint'          => 'Kaudalya/Nagendra',
        'veda'           => 'Samaveda',
        'branch'         => 'Kouthmi/Kauttham',
        'sutra'          => 'Aslayin',
    ],
    [
        'caste'          => 'Agarwal',
        'gotra'          => 'Singhal/Singla',
        'original_gotra' => 'Shandalya',
        'lord'           => 'Sindhupati',
        'saint'          => 'Shringi/Shandilya',
        'veda'           => 'Samaveda',
        'branch'         => 'Koyumi/Kauttham',
        'sutra'          => 'Gobhil',
    ],
    [
        'caste'          => 'Agarwal',
        'gotra'          => 'Tayal',
        'original_gotra' => 'Taitireya',
        'lord'           => 'Tarachand',
        'saint'          => 'Saakal/Taitireya',
        'veda'           => 'Yajurveda/Kri',
        'branch'         => 'Madhyadini/Aausthambh',
        'sutra'          => 'Kaatyayni',
    ],
    [
        'caste'          => 'Agarwal',
        'gotra'          => 'Tingal/Tunghal',
        'original_gotra' => 'Taandav',
        'lord'           => 'Tambolkarna',
        'saint'          => 'Shandilya/Tandya',
        'veda'           => 'Yajurveda',
        'branch'         => 'Madhyadini/Madhuri',
        'sutra'          => 'Kaatyayni',
    ],
    /*[
        'caste'           => 'Agarwal',
        'gotra'          => '',
        'original_gotra' => '',
        'lord'            => '',
        'saint'           => '',
        'veda'            => '',
        'branch'          => '',
        'sutra'           => '',
    ],
    */
];

$this->seeder->table('castes')->data($data)->rowQuantity(count($data));
